#!/bin/sh
NAME=$1
TEMPLATEDIR="`cd \`dirname "$0"\` && pwd`"
TEMPLATEREMOTE="git@github.com:TheSystemDevelopmentKit/Inverter_simulation.git"

if [ ! -d "$NAME" ]; then
    git clone ${TEMPLATEREMOTE} $NAME
else
    echo "Simulation exists!!"
    exit 0
fi
#cp $TEMPLATEDIR/configure $NAME
exit


